require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  DisplayCopNames: true
  TargetRubyVersion: 3.0.1
  Include:
    - '**/*.rb'
    - '**/*.rake'
    - '**/*.spec'
    - '**/Gemfile'
  Exclude:
    - bin/**
    - node_modules/**/*
    - db/schema.rb

Style/FrozenStringLiteralComment:
  Enabled: true

Style/RedundantFetchBlock:
  Safe: true

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc
  Exclude:
    - db/**/*

Metrics/AbcSize:
  Exclude:
    - db/**/*

Metrics/BlockLength:
  Exclude:
    - db/**/*
    - spec/**/*_spec.rb
    - lib/tasks/*.rake
    - config/environments/*.rb
    - config/routes.rb

Rails:
  Enabled: true
Rails/SkipsModelValidations:
  Exclude:
    - db/seeds.rb
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 20
  Exclude:
    - spec/**/*_spec.rb
RSpec/MultipleMemoizedHelpers:
  Exclude:
    - db/**/*
    - spec/**/*_spec.rb
Metrics/ClassLength:
  Exclude:
    - app/controllers/api/v1/base_controller.rb