# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/recipe_requests', type: :request do
  # RecipeRequest. As you add validations to RecipeRequest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      RecipeRequest.create! valid_attributes
      get recipe_requests_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      recipe_request = RecipeRequest.create! valid_attributes
      get recipe_request_url(recipe_request)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_recipe_request_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      recipe_request = RecipeRequest.create! valid_attributes
      get edit_recipe_request_url(recipe_request)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new RecipeRequest' do
        expect do
          post recipe_requests_url, params: { recipe_request: valid_attributes }
        end.to change(RecipeRequest, :count).by(1)
      end

      it 'redirects to the created recipe_request' do
        post recipe_requests_url, params: { recipe_request: valid_attributes }
        expect(response).to redirect_to(recipe_request_url(RecipeRequest.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new RecipeRequest' do
        expect do
          post recipe_requests_url, params: { recipe_request: invalid_attributes }
        end.to change(RecipeRequest, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post recipe_requests_url, params: { recipe_request: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested recipe_request' do
        recipe_request = RecipeRequest.create! valid_attributes
        patch recipe_request_url(recipe_request), params: { recipe_request: new_attributes }
        recipe_request.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the recipe_request' do
        recipe_request = RecipeRequest.create! valid_attributes
        patch recipe_request_url(recipe_request), params: { recipe_request: new_attributes }
        recipe_request.reload
        expect(response).to redirect_to(recipe_request_url(recipe_request))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        recipe_request = RecipeRequest.create! valid_attributes
        patch recipe_request_url(recipe_request), params: { recipe_request: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested recipe_request' do
      recipe_request = RecipeRequest.create! valid_attributes
      expect do
        delete recipe_request_url(recipe_request)
      end.to change(RecipeRequest, :count).by(-1)
    end

    it 'redirects to the recipe_requests list' do
      recipe_request = RecipeRequest.create! valid_attributes
      delete recipe_request_url(recipe_request)
      expect(response).to redirect_to(recipe_requests_url)
    end
  end
end
